name: Mega Integration

on:
  push:
    branches:
      - main

jobs:
  mega_integration:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'

      # Step 3: Configure Git user for authentication
      - name: Configure Git user
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          npm install -g npm@latest
          npm install

      # Step 5: Update package.json with required dependencies
      - name: Update package.json
        run: |
          if [ -f package.json ]; then
            echo "Adding required dependencies to package.json"
            npm install megajs --save
          fi

      # Step 6: Run Mega script
      - name: Run Mega script
        run: node downloadMegaFolders.js

      # Step 7: Commit and push changes
      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m 'Update Mega script dependencies and output'
            git push origin HEAD:main
          fi